spring.application.name=backend
# ??? DataSource ???????????????????????????????????????????????
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.username=admin
#spring.datasource.password=secret123
spring.datasource.url=jdbc:postgresql://dpg-d7ie8lt7vvec738vn850-a.oregon-postgres.render.com/gym_db_ensf?sslmode=require
spring.datasource.username=gym_db_ensf_user
spring.datasource.password=5mNsge1qRktIFeTmdnzmc7fvTyqM1jT5
spring.datasource.driver-class-name=org.postgresql.Driver

# ??? Connection Pool (HikariCP - Spring Boot default) ?????????
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# ??? JPA / Hibernate ??????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}